package com.netcracker.cloud.trainings.extensions.greeting;

import com.netcracker.smartplug.annotations.Implementation;

@Implementation(forInterface = MessageGenerator.class, minAllowedVersion = "1.0.0")
public class MessageGeneratorImpl implements MessageGenerator {

    public GeneratedMessage generate(MessageGenerationParams messageGenerationParams) {
        MessageGenerator defaultGenerator = new DefaultMessageGenerator();
        GeneratedMessage defaultMessage = defaultGenerator.generate(messageGenerationParams);

        return new GeneratedMessage(defaultMessage.getMessageContent() + " This message was generated by Smartplug plugin");
    }
}